#!/bin/bash
/home/admin/smart-house/UI/service.status.cmd
/home/admin/smart-house/Editor/service.status.cmd
/home/admin/smart-house/Log/service.status.cmd
/home/admin/smart-house/Sensor.Random/service.status.cmd
/home/admin/smart-house/Sensor.Mqtt/service.status.cmd
/home/admin/smart-house/Control.GMail/service.status.cmd
/home/admin/smart-house/Control.Telegram/service.status.cmd
/home/admin/smart-house/Command/service.status.cmd