#!/bin/bash
/home/admin/smart-house/UI/service.delete.cmd
/home/admin/smart-house/Editor/service.delete.cmd
/home/admin/smart-house/Log/service.delete.cmd
/home/admin/smart-house/Sensor.Random/service.delete.cmd
/home/admin/smart-house/Sensor.Mqtt/service.delete.cmd
/home/admin/smart-house/Control.GMail/service.delete.cmd
/home/admin/smart-house/Control.Telegram/service.delete.cmd
/home/admin/smart-house/Command/service.delete.cmd