#!/bin/bash
/home/admin/smart-house/UI/service.stop.cmd
/home/admin/smart-house/Editor/service.stop.cmd
/home/admin/smart-house/Log/service.stop.cmd
/home/admin/smart-house/Sensor.Random/service.stop.cmd
/home/admin/smart-house/Sensor.Mqtt/service.stop.cmd
/home/admin/smart-house/Control.GMail/service.stop.cmd
/home/admin/smart-house/Control.Telegram/service.stop.cmd
/home/admin/smart-house/Command/service.stop.cmd
/home/admin/smart-house/Mqtt.Test/service.stop.cmd