#!/bin/bash
/home/admin/smart-house/Command/test.sh
/home/admin/smart-house/Control.GMail/test.sh
/home/admin/smart-house/Control.Telegram/test.sh
/home/admin/smart-house/Editor/test.sh
/home/admin/smart-house/Home/test.sh
/home/admin/smart-house/Log/test.sh
/home/admin/smart-house/Mqtt.Test/test.sh
/home/admin/smart-house/Scene/test.sh
/home/admin/smart-house/Schedule/test.sh
/home/admin/smart-house/Sensor.BTooth/test.sh
/home/admin/smart-house/Sensor.Currency/test.sh
/home/admin/smart-house/Sensor.Flood/test.sh
/home/admin/smart-house/Sensor.Garage/test.sh
/home/admin/smart-house/Sensor.GMail/test.sh
/home/admin/smart-house/Sensor.Huricane/test.sh
/home/admin/smart-house/Sensor.Image/test.sh
/home/admin/smart-house/Sensor.IPv4/test.sh
/home/admin/smart-house/Sensor.IPv6/test.sh
/home/admin/smart-house/Sensor.Kasa/test.sh
/home/admin/smart-house/Sensor.Kitchen/test.sh
/home/admin/smart-house/Sensor.Level/test.sh
/home/admin/smart-house/Sensor.LiveIPs/test.sh
/home/admin/smart-house/Sensor.Metal/test.sh
/home/admin/smart-house/Sensor.Mqtt/test.sh
/home/admin/smart-house/Sensor.Netro/test.sh
/home/admin/smart-house/Sensor.Pool/test.sh
/home/admin/smart-house/Sensor.IPv4/test.sh
/home/admin/smart-house/Sensor.Random/test.sh
/home/admin/smart-house/Sensor.Roomba/test.sh
/home/admin/smart-house/Sensor.Thermostat/test.sh
/home/admin/smart-house/Sensor.Weather/test.sh
/home/admin/smart-house/Sensor.Web/test.sh
/home/admin/smart-house/Shared/test.sh
/home/admin/smart-house/UI/test.sh
